idf_component_register(
    SRCS 
        "main.c"
        "wifi/wifi_helper.c"
        "config/config_manager.c"
        "api_client/api_client.c"
        "sensors/temperature/temp_sensor.c"
    INCLUDE_DIRS 
        "."
        "wifi"
        "config"
        "api_client"
        "sensors/temperature"
    REQUIRES 
        esp_adc 
        esp_wifi 
        esp_http_client
        esp_http_server
        esp_event 
        nvs_flash
        cjson
)
